### ISSUE TITLE
Dependance

### ISSUE THREAD

**Issue by NullHF** [Subterranean-Security/Sandpolis#1]
Hello can you write me all dependance needed ? i not succes import in exclipse without error so i can't build 
Sorry my bad english

**Comment by NullHF** [comment]
If you want help for testing or search for code implantation (more feature) i can help you

**Comment by NullHF** [comment]
Okay !

**Comment by cilki** [comment]
**Update:** I'm down to 26 unstaged files. It should be possible to build now, but the gui won't run until everything is committed.
